### ISSUE TITLE
BUG-REPORT: Main Branch interactive session doesn't quit on C-d

### ISSUE THREAD

**Issue by Haiz14** [mosajjal/bard-cli#5]
did 
```bash
git clone <this-repo>
cd bard-cli
go mod tidy && go build
```
Ran interactive session but C-d doesn't quit the interactive session.

-------

p.s. Thks for your awesome work, I can finally automate some part of my ai use. Wanna contribute too, any directions ?

**Comment by mosajjal** [comment]
Hi. 

yes Ctrl+D is outdated (since the underlying dependency has changed) and the comment will be removed. it's now replaced by `!quit`. 

as for the future direction of the project, first we need to wait a few weeks to see if Google is actually happy with a reverse-engineered port of their API turned into a FOSS project. if they allow it to happen, I'm keen to build this as a browser/vscode extension, vim plugin, TUI etc to make it as accessible as possible.

**Comment by mosajjal** [comment]
fixed in https://github.com/mosajjal/bard-cli/releases/tag/v0.3.2
